__title__ = "protobuf-doc-autogen"
__author__ = "mintel"
__summary__ = "auto-generate markdown from .proto files"
__author_email__ = "mintel.com"
__uri__ = "https://gitlab.com/mintel/personal-dev/apage/protoc-autodoc"
__version__ = "0.1.1"
